" Name:         Cryslominsa
" Description:  Archived Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/archived-colors/
" License:      MIT && Anti-996
" Last Updated: Sun 04 Aug 2019 05:34:44 PM CST

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'cryslominsa'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#c0c7d0', '#e581a4', '#85c1a1', '#babf75',
        \ '#86b7e3', '#b7a3ea', '#71bfc5', '#88929f', '#c0c7d0', '#e581a4',
        \ '#85c1a1', '#babf75', '#86b7e3', '#b7a3ea', '#71bfc5', '#88929f']
  if has('nvim')
    let g:terminal_color_0 = '#c0c7d0'
    let g:terminal_color_1 = '#e581a4'
    let g:terminal_color_2 = '#85c1a1'
    let g:terminal_color_3 = '#babf75'
    let g:terminal_color_4 = '#86b7e3'
    let g:terminal_color_5 = '#b7a3ea'
    let g:terminal_color_6 = '#71bfc5'
    let g:terminal_color_7 = '#88929f'
    let g:terminal_color_8 = '#c0c7d0'
    let g:terminal_color_9 = '#e581a4'
    let g:terminal_color_10 = '#85c1a1'
    let g:terminal_color_11 = '#babf75'
    let g:terminal_color_12 = '#86b7e3'
    let g:terminal_color_13 = '#b7a3ea'
    let g:terminal_color_14 = '#71bfc5'
    let g:terminal_color_15 = '#88929f'
  endif
  hi Fg guifg=#c0c7d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Red guifg=#e581a4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Yellow guifg=#babf75 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Green guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cyan guifg=#71bfc5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Blue guifg=#86b7e3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Purple guifg=#b7a3ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Grey guifg=#88929f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#c0c7d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#c0c7d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#c0c7d0 guibg=#323f4f guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#c0c7d0 guibg=#323f4f guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#88929f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#c0c7d0 guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#88929f guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#364b47 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#2b4463 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#492f39 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#414232 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#323f4f guibg=#323f4f guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e581a4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#babf75 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#86b7e3 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#b7a3ea guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#88929f guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#88929f guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#475567 guisp=NONE gui=underline cterm=underline
  hi Search guifg=NONE guibg=#475567 guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#88929f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#c0c7d0 guibg=#475567 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#323f4f guibg=#71bfc5 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#475567 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#88929f guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#e581a4 guibg=NONE guisp=#e581a4 gui=NONE cterm=NONE
  hi SpellCap guifg=#babf75 guibg=NONE guisp=#babf75 gui=NONE cterm=NONE
  hi SpellLocal guifg=#86b7e3 guibg=NONE guisp=#86b7e3 gui=NONE cterm=NONE
  hi SpellRare guifg=#b7a3ea guibg=NONE guisp=#b7a3ea gui=NONE cterm=NONE
  hi StatusLine guifg=#c0c7d0 guibg=#475567 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#88929f guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#c0c7d0 guibg=#475567 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#88929f guibg=#3d4b5c guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#323f4f guibg=#86b7e3 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#475567 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#475567 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#475567 guisp=NONE gui=italic cterm=italic
  hi WildMenu guifg=#323f4f guibg=#71bfc5 guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=#c0c7d0 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#88929f guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#c0c7d0 guibg=#323f4f guisp=NONE gui=bold cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi Error guifg=#e581a4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#e581a4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#e581a4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#e581a4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#e581a4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#babf75 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#babf75 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#babf75 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#85c1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#71bfc5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#71bfc5 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi StorageClass guifg=#71bfc5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#71bfc5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#71bfc5 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Operator guifg=#71bfc5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#86b7e3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#86b7e3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#86b7e3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#86b7e3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#b7a3ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#b7a3ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#b7a3ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#b7a3ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#b7a3ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#c0c7d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#88929f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#88929f guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#88929f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Fg ctermfg=251 ctermbg=NONE cterm=NONE
  hi Red ctermfg=211 ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=143 ctermbg=NONE cterm=NONE
  hi Green ctermfg=115 ctermbg=NONE cterm=NONE
  hi Cyan ctermfg=73 ctermbg=NONE cterm=NONE
  hi Blue ctermfg=110 ctermbg=NONE cterm=NONE
  hi Purple ctermfg=147 ctermbg=NONE cterm=NONE
  hi Grey ctermfg=246 ctermbg=NONE cterm=NONE
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=251 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=251 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=251 ctermbg=237 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=251 ctermbg=237 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=239 cterm=NONE
  hi Conceal ctermfg=246 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=239 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=239 cterm=NONE
  hi CursorLineNr ctermfg=251 ctermbg=239 cterm=NONE
  hi LineNr ctermfg=246 ctermbg=239 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=239 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=238 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=24 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=238 cterm=NONE
  hi Directory ctermfg=115 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=237 ctermbg=237 cterm=NONE
  hi ErrorMsg ctermfg=211 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=143 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=110 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=147 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=246 ctermbg=239 cterm=NONE
  hi Folded ctermfg=246 ctermbg=239 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=240 cterm=underline
  hi Search ctermfg=NONE ctermbg=240 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=246 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=251 ctermbg=240 cterm=NONE
  hi PmenuSel ctermfg=237 ctermbg=73 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=240 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=246 cterm=NONE
  hi Question ctermfg=115 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=211 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=143 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=110 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=147 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=251 ctermbg=240 cterm=NONE
  hi StatusLineNC ctermfg=246 ctermbg=239 cterm=NONE
  hi TabLine ctermfg=251 ctermbg=240 cterm=NONE
  hi TabLineFill ctermfg=246 ctermbg=239 cterm=NONE
  hi TabLineSel ctermfg=237 ctermbg=110 cterm=NONE
  hi VertSplit ctermfg=240 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=240 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=240 cterm=italic
  hi WildMenu ctermfg=237 ctermbg=73 cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=251 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=246 cterm=NONE
  hi ToolbarButton ctermfg=251 ctermbg=237 cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi Error ctermfg=211 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=211 ctermbg=NONE cterm=NONE
  hi Define ctermfg=211 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=211 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=211 ctermbg=NONE cterm=NONE
  hi Special ctermfg=143 ctermbg=NONE cterm=NONE
  hi Type ctermfg=143 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=143 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=115 ctermbg=NONE cterm=NONE
  hi String ctermfg=115 ctermbg=NONE cterm=NONE
  hi Character ctermfg=115 ctermbg=NONE cterm=NONE
  hi Number ctermfg=115 ctermbg=NONE cterm=NONE
  hi Float ctermfg=115 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=115 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=73 ctermbg=NONE cterm=NONE
  hi Title ctermfg=73 ctermbg=NONE cterm=bold
  hi StorageClass ctermfg=73 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=73 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=73 ctermbg=NONE cterm=italic
  hi Operator ctermfg=73 ctermbg=NONE cterm=NONE
  hi Label ctermfg=110 ctermbg=NONE cterm=NONE
  hi Function ctermfg=110 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=110 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=110 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=147 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=147 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=147 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=147 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=147 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=251 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=246 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=246 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=246 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=LightGrey cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=Blue ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=Magenta ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi Search ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=Cyan cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Grey cterm=NONE
  hi Question ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=White ctermbg=LightGrey cterm=NONE
  hi StatusLineNC ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=White ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=Blue cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=LightGrey cterm=italic
  hi WildMenu ctermfg=Black ctermbg=Cyan cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Red ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Title ctermfg=Cyan ctermbg=NONE cterm=bold
  hi StorageClass ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Cyan ctermbg=NONE cterm=italic
  hi Operator ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Label ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Blue ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: background    #323f4f           ~                 Black
" Color: foreground    #c0c7d0           ~                 White
" Color: red           #e581a4           ~                 Red
" Color: yellow        #babf75           ~                 Yellow
" Color: green         #85c1a1           ~                 Green
" Color: cyan          #71bfc5           ~                 Cyan
" Color: blue          #86b7e3           ~                 Blue
" Color: purple        #b7a3ea           ~                 Magenta
" Color: grey          #88929f           ~                 Grey
" Color: background_alt #3d4b5c          ~                 LightGrey
" Color: background_grey #475567         ~                 LightGrey
" Color: background_red #492f39          ~                 LightRed
" Color: background_green #364b47        ~                 LightGreen
" Color: background_yellow #414232       ~                 LightYellow
" Color: background_blue #2b4463         ~                 LightBlue
" Term colors: foreground red green yellow blue purple cyan grey
" Term colors: foreground red green yellow blue purple cyan grey
" vim: et ts=2 sw=2
