" Name:         Dark Luma
" Description:  Dark, minimalist scheme with high contrast and balanced brightness
" Author:       David Golden <xdg@xdg.me>
" Maintainer:   David Golden <xdg@xdg.me>
" Website:      https://github.com/xdg/vim-darkluma
" License:      MIT
" Last Updated: Tue Oct 29 17:15:32 2019

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'darkluma'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

hi! link Whitespace NonText
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#e04660', '#139b00', '#ccaa00',
        \ '#6680ff', '#af0dec', '#3aada5', '#cccccc', '#7f7f7f', '#ff99aa',
        \ '#28f000', '#e6bf00', '#a3b3ff', '#ea80ff', '#00febb', '#ffffff']
  if has('nvim')
    let g:terminal_color_0 = '#000000'
    let g:terminal_color_1 = '#e04660'
    let g:terminal_color_2 = '#139b00'
    let g:terminal_color_3 = '#ccaa00'
    let g:terminal_color_4 = '#6680ff'
    let g:terminal_color_5 = '#af0dec'
    let g:terminal_color_6 = '#3aada5'
    let g:terminal_color_7 = '#cccccc'
    let g:terminal_color_8 = '#7f7f7f'
    let g:terminal_color_9 = '#ff99aa'
    let g:terminal_color_10 = '#28f000'
    let g:terminal_color_11 = '#e6bf00'
    let g:terminal_color_12 = '#a3b3ff'
    let g:terminal_color_13 = '#ea80ff'
    let g:terminal_color_14 = '#00febb'
    let g:terminal_color_15 = '#ffffff'
  endif
  hi Normal guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#7f7f7f guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen guifg=#ccaa00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#e04660 guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#7f7f7f guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#7f7f7f guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#7f7f7f guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#cccccc guibg=#191919 guisp=NONE gui=reverse cterm=reverse
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#139b00 guibg=#191919 guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#ccaa00 guibg=#191919 guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#e04660 guibg=#191919 guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#ccaa00 guibg=#191919 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi FoldColumn guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#cccccc guibg=#7f7f7f guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#000000 guibg=#cccccc guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#000000 guibg=#ccaa00 guisp=NONE gui=NONE cterm=NONE
  hi Substitute guifg=#000000 guibg=#ccaa00 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#7f7f7f guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e04660 guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#7f7f7f guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#cccccc guibg=#001a99 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#cccccc guibg=#7f7f7f guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#cccccc guibg=#7f7f7f guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#cccccc guibg=#7f7f7f guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ccaa00 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#cccccc guibg=#665500 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#cccccc guibg=#191919 guisp=#e04660 gui=undercurl cterm=undercurl
  hi SpellCap guifg=#cccccc guibg=#191919 guisp=#6680ff gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#cccccc guibg=#191919 guisp=#af0dec gui=undercurl cterm=undercurl
  hi SpellRare guifg=#cccccc guibg=#191919 guisp=#3aada5 gui=reverse,undercurl cterm=reverse,undercurl
  hi TabLine guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#cccccc guibg=#191919 guisp=NONE gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#7f7f7f guibg=#7f7f7f guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#6680ff guibg=#191919 guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#3aada5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#cccccc guibg=#000000 guisp=NONE gui=reverse cterm=reverse
  hi Identifier guifg=#cccccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#cccccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#6680ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#3aada5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#af0dec guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#af0dec guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#cccccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ff99aa guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#139b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#3aada5 guibg=NONE guisp=#3aada5 gui=undercurl cterm=undercurl
  if get(g:, 'darkluma_dark_comments', 0)
    hi Comment guifg=#7f7f7f guibg=NONE guisp=NONE gui=italic cterm=italic
    if !s:italics
      hi Comment gui=NONE cterm=NONE
    endif
  else
    hi Comment guifg=#c07e4d guibg=NONE guisp=NONE gui=italic cterm=italic
    if !s:italics
      hi Comment gui=NONE cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=252 ctermbg=234 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  hi NonText ctermfg=244 ctermbg=234 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=178 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=197 ctermbg=234 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=244 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=244 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=252 ctermbg=234 cterm=NONE
  hi EndOfBuffer ctermfg=244 ctermbg=234 cterm=NONE
  hi Cursor ctermfg=252 ctermbg=234 cterm=reverse
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi DiffAdd ctermfg=34 ctermbg=234 cterm=reverse
  hi DiffChange ctermfg=178 ctermbg=234 cterm=reverse
  hi DiffDelete ctermfg=197 ctermbg=234 cterm=reverse
  hi DiffText ctermfg=178 ctermbg=234 cterm=bold,reverse
  hi FoldColumn ctermfg=252 ctermbg=234 cterm=NONE
  hi Folded ctermfg=252 ctermbg=244 cterm=NONE
  hi IncSearch ctermfg=16 ctermbg=252 cterm=NONE
  hi Search ctermfg=16 ctermbg=178 cterm=NONE
  hi Substitute ctermfg=16 ctermbg=178 cterm=NONE
  hi CursorLineNr ctermfg=252 ctermbg=234 cterm=NONE
  hi LineNr ctermfg=244 ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=252 ctermbg=234 cterm=NONE
  hi ErrorMsg ctermfg=197 ctermbg=234 cterm=NONE
  hi WarningMsg ctermfg=252 ctermbg=234 cterm=NONE
  hi ModeMsg ctermfg=244 ctermbg=234 cterm=NONE
  hi MoreMsg ctermfg=252 ctermbg=234 cterm=NONE
  hi Question ctermfg=252 ctermbg=234 cterm=NONE
  hi StatusLine ctermfg=252 ctermbg=19 cterm=NONE
  hi StatusLineNC ctermfg=252 ctermbg=244 cterm=NONE
  hi Pmenu ctermfg=252 ctermbg=244 cterm=NONE
  hi PmenuSbar ctermfg=252 ctermbg=244 cterm=NONE
  hi PmenuSel ctermfg=178 ctermbg=235 cterm=NONE
  hi PmenuThumb ctermfg=252 ctermbg=58 cterm=NONE
  hi SpellBad ctermfg=252 ctermbg=234 cterm=underline
  hi SpellCap ctermfg=252 ctermbg=234 cterm=underline
  hi SpellLocal ctermfg=252 ctermbg=234 cterm=underline
  hi SpellRare ctermfg=252 ctermbg=234 cterm=reverse,underline
  hi TabLine ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineFill ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineSel ctermfg=252 ctermbg=234 cterm=NONE
  hi Title ctermfg=252 ctermbg=234 cterm=NONE
  hi ToolbarButton ctermfg=252 ctermbg=234 cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi VertSplit ctermfg=244 ctermbg=244 cterm=NONE
  hi WildMenu ctermfg=252 ctermbg=234 cterm=NONE
  hi Directory ctermfg=69 ctermbg=234 cterm=NONE
  hi Constant ctermfg=37 ctermbg=NONE cterm=NONE
  hi Error ctermfg=252 ctermbg=16 cterm=reverse
  hi Identifier ctermfg=252 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=252 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=69 ctermbg=NONE cterm=NONE
  hi Label ctermfg=37 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=129 ctermbg=NONE cterm=NONE
  hi Special ctermfg=129 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=252 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=211 ctermbg=NONE cterm=NONE
  hi Type ctermfg=34 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=37 ctermbg=NONE cterm=underline
  if get(g:, 'darkluma_dark_comments', 0)
    hi Comment ctermfg=244 ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  else
    hi Comment ctermfg=173 ctermbg=NONE cterm=italic
    if !s:italics
      hi Comment cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         rgb(  0,   0,   0)        ~
" Color: red           rgb(224,  70,  96)        ~
" Color: orange        rgb(192, 126,  77)        ~
" Color: green         rgb( 19, 155,   0)        ~
" Color: yellow        rgb(204, 170,   0)        ~
" Color: blue          rgb(102, 128, 255)        ~
" Color: magenta       rgb(175,  13, 236)        ~
" Color: cyan          rgb( 58, 173, 165)        ~
" Color: white         rgb(204, 204, 204)        ~
" Color: gray          rgb(127, 127, 127)        ~
" Color: brightred     rgb(255, 153, 170)        ~
" Color: brightgreen   rgb( 40, 240,   0)        ~
" Color: brightyellow  rgb(230, 191,   0)        ~
" Color: brightblue    rgb(163, 179, 255)        ~
" Color: brightmagenta rgb(234, 128, 255)        ~
" Color: brightcyan    rgb(  0, 254, 187)        ~
" Color: brightwhite   rgb(255, 255, 255)        ~
" Color: black85pct    rgb( 38,  38,  38)        ~
" Color: black90pct    rgb( 25,  25,  25)        ~
" Color: darkgold      rgb(102,  85,   0)        ~
" Color: darkgreen     rgb( 17, 102,   0)        ~
" Color: darkblue      rgb(  0,  26, 153)        ~
" Term colors: black red green yellow blue magenta cyan white
" Term colors: gray brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
