" Name:         focusedpanic
" Author:       Tobias Jammer <tobiasjammer@gmail.com>
" Maintainer:   Tobias Jammer <tobiasjammer@gmail.com>
" License:      MIT
" Last Updated: Fri 24 Jan 2020 18:21:54 CET

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'focusedpanic'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Normal
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor
hi! link cStorageClass Statement
hi! link cppModifier Statement
hi! link ALEWarning WarningMsg
hi! link ALEWarningSign WarningMsg
hi! link ALEError ErrorMsg
hi! link ALEErrorSign ErrorMsg
hi! link RubyDefine Statement

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#0c151e', '#ff4143', '#3de163', '#ffcc4b',
        \ '#1094c3', '#7f4efe', '#3abc9c', '#fefefe', '#17556f', '#ff4143',
        \ '#3de163', '#ffcc4b', '#1094c3', '#7f4efe', '#3abc9c', '#0b2a37']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#fefefe guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#fefefe guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#0b2a37 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#0b2a37 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#3de163 guibg=#0c151e guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#ffcc4b guibg=#0c151e guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#ff4143 guibg=#0c151e guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#fefefe guibg=#0c151e guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#ffcc4b guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#17556f guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ff4143 guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#fefefe guibg=#0c151e guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=#ffcc4b guibg=#0c151e guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#fefefe guibg=#0c151e guisp=NONE gui=underline cterm=underline
  hi ModeMsg guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#fefefe guibg=#0b2a37 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#1094c3 guibg=#0b2a37 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#ffcc4b guibg=#0c151e guisp=NONE gui=standout cterm=standout
  hi SignColumn guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#fefefe guibg=#0c151e guisp=#ff4143 gui=NONE cterm=NONE
  hi SpellCap guifg=#fefefe guibg=#0c151e guisp=#1094c3 gui=NONE cterm=NONE
  hi SpellLocal guifg=#fefefe guibg=#0c151e guisp=#7f4efe gui=NONE cterm=NONE
  hi SpellRare guifg=#fefefe guibg=#0c151e guisp=#3abc9c gui=reverse cterm=reverse
  hi StatusLine guifg=#fefefe guibg=#0c151e guisp=NONE gui=underline cterm=underline
  hi StatusLineNC guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#0b2a37 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#ffcc4b guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#ffcc4b guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#17556f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#1094c3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#fefefe guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#fefefe guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#fefefe guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#fefefe guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Special guifg=#fefefe guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#3de163 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Todo guifg=#ffcc4b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Type guifg=#fefefe guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Underlined guifg=#fefefe guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#0c151e guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#fefefe guibg=#0c151e guisp=NONE gui=bold cterm=bold
  hi GitGutterAdd guifg=#3de163 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#ffcc4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ff4143 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#ffcc4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=231 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=231 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=231 ctermbg=233 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=231 ctermbg=233 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=233 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=231 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=231 cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=233 cterm=NONE
  hi DiffAdd ctermfg=41 ctermbg=233 cterm=reverse
  hi DiffChange ctermfg=221 ctermbg=233 cterm=reverse
  hi DiffDelete ctermfg=203 ctermbg=233 cterm=reverse
  hi DiffText ctermfg=231 ctermbg=233 cterm=bold,reverse
  hi Directory ctermfg=221 ctermbg=233 cterm=NONE
  hi EndOfBuffer ctermfg=24 ctermbg=233 cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=233 cterm=NONE
  hi FoldColumn ctermfg=231 ctermbg=233 cterm=NONE
  hi Folded ctermfg=231 ctermbg=233 cterm=italic
  hi IncSearch ctermfg=221 ctermbg=233 cterm=reverse
  hi LineNr ctermfg=231 ctermbg=233 cterm=NONE
  hi MatchParen ctermfg=231 ctermbg=233 cterm=underline
  hi ModeMsg ctermfg=231 ctermbg=233 cterm=NONE
  hi MoreMsg ctermfg=231 ctermbg=233 cterm=NONE
  hi NonText ctermfg=231 ctermbg=233 cterm=NONE
  hi Pmenu ctermfg=231 ctermbg=231 cterm=NONE
  hi PmenuSbar ctermfg=231 ctermbg=233 cterm=NONE
  hi PmenuSel ctermfg=31 ctermbg=231 cterm=NONE
  hi PmenuThumb ctermfg=231 ctermbg=233 cterm=NONE
  hi Question ctermfg=231 ctermbg=233 cterm=NONE
  hi Search ctermfg=221 ctermbg=233 cterm=reverse
  hi SignColumn ctermfg=231 ctermbg=233 cterm=NONE
  hi SpecialKey ctermfg=231 ctermbg=233 cterm=NONE
  hi SpellBad ctermfg=231 ctermbg=233 cterm=NONE
  hi SpellCap ctermfg=231 ctermbg=233 cterm=NONE
  hi SpellLocal ctermfg=231 ctermbg=233 cterm=NONE
  hi SpellRare ctermfg=231 ctermbg=233 cterm=reverse
  hi StatusLine ctermfg=231 ctermbg=233 cterm=underline
  hi StatusLineNC ctermfg=231 ctermbg=233 cterm=NONE
  hi TabLine ctermfg=231 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=231 ctermbg=233 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=233 cterm=NONE
  hi Title ctermfg=231 ctermbg=233 cterm=NONE
  hi VertSplit ctermfg=231 ctermbg=233 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=231 cterm=NONE
  hi VisualNOS ctermfg=231 ctermbg=233 cterm=NONE
  hi WarningMsg ctermfg=221 ctermbg=233 cterm=NONE
  hi WildMenu ctermfg=221 ctermbg=233 cterm=NONE
  hi Comment ctermfg=24 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=31 ctermbg=NONE cterm=NONE
  hi Error ctermfg=231 ctermbg=233 cterm=NONE
  hi Identifier ctermfg=231 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=231 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=231 ctermbg=NONE cterm=bold
  hi Special ctermfg=231 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=41 ctermbg=NONE cterm=bold
  hi Todo ctermfg=221 ctermbg=NONE cterm=bold
  hi Type ctermfg=231 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=231 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi ToolbarButton ctermfg=231 ctermbg=233 cterm=bold
  hi GitGutterAdd ctermfg=41 ctermbg=NONE cterm=NONE
  hi GitGutterChange ctermfg=221 ctermbg=NONE cterm=NONE
  hi GitGutterDelete ctermfg=203 ctermbg=NONE cterm=NONE
  hi GitGutterChangeDelete ctermfg=221 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=White cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=White cterm=NONE
  hi CursorLineNr ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=Black cterm=reverse
  hi DiffText ctermfg=LightGrey ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi FoldColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Black cterm=italic
  hi IncSearch ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi LineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=LightGrey ctermbg=Black cterm=underline
  hi ModeMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi NonText ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=LightGrey ctermbg=White cterm=NONE
  hi PmenuSbar ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=DarkBlue ctermbg=White cterm=NONE
  hi PmenuThumb ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Search ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi SignColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellCap ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellLocal ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellRare ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi StatusLine ctermfg=LightGrey ctermbg=Black cterm=underline
  hi StatusLineNC ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=White cterm=NONE
  hi VisualNOS ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WarningMsg ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Error ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Identifier ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi Special ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkGreen ctermbg=NONE cterm=bold
  hi Todo ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Type ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi Underlined ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  hi GitGutterAdd ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi GitGutterChange ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi GitGutterDelete ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi GitGutterChangeDelete ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #0c151e        ~         Black
" Color: red           #ff4143        ~         DarkRed
" Color: green         #3de163        ~         DarkGreen
" Color: yellow        #ffcc4b        ~         DarkYellow
" Color: blue          #1094c3        ~         DarkBlue
" Color: magenta       #7f4efe        ~         DarkMagenta
" Color: cyan          #3abc9c        ~         DarkCyan
" Color: white         #fefefe        ~         LightGrey
" Color: brightblack   #17556f        ~         DarkGrey
" Color: brightred     #ff4143        ~         LightRed
" Color: brightgreen   #3de163        ~         LightGreen
" Color: brightyellow  #ffcc4b        ~         LightYellow
" Color: brightblue    #1094c3        ~         LightBlue
" Color: brightmagenta #7f4efe        ~         LightMagenta
" Color: brightcyan    #3abc9c        ~         LightCyan
" Color: brightwhite   #0b2a37       231        White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
