" Name:         Grimoire
" Description:  🕮  Non-dark, Retro, Eye-friendly Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-grimoire/
" License:      MIT && Anti-996
" Last Updated: Thu 18 Jul 2019 03:31:56 PM CST

" Generated by Colortemplate v2.0.0

set background=light

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'grimoire'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Structure Type
hi! link Boolean Constant
hi! link Define PreProc
hi! link SpecialChar Special
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#674529', '#963d3f', '#3b604d', '#8b4830',
        \ '#49576d', '#6f4767', '#3a6065', '#918175', '#674529', '#963d3f',
        \ '#3b604d', '#8b4830', '#49576d', '#6f4767', '#3a6065', '#918175']
  if has('nvim')
    let g:terminal_color_0 = '#674529'
    let g:terminal_color_1 = '#963d3f'
    let g:terminal_color_2 = '#3b604d'
    let g:terminal_color_3 = '#8b4830'
    let g:terminal_color_4 = '#49576d'
    let g:terminal_color_5 = '#6f4767'
    let g:terminal_color_6 = '#3a6065'
    let g:terminal_color_7 = '#918175'
    let g:terminal_color_8 = '#674529'
    let g:terminal_color_9 = '#963d3f'
    let g:terminal_color_10 = '#3b604d'
    let g:terminal_color_11 = '#8b4830'
    let g:terminal_color_12 = '#49576d'
    let g:terminal_color_13 = '#6f4767'
    let g:terminal_color_14 = '#3a6065'
    let g:terminal_color_15 = '#918175'
  endif
  if get(g:, 'light_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#674529 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#674529 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#674529 guibg=#c2a273 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#674529 guibg=#c2a273 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#c2a273 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#7e7268 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#674529 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#7fa37f guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#7f8ca3 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#c27773 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#ce9861 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#674529 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#c2a273 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#963d3f guibg=#c2a273 guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#7e7268 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#7e7268 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#ae9168 guisp=NONE gui=underline cterm=underline
  hi LineNr guifg=#7e7268 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg guifg=#634022 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#634022 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#7e7268 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#674529 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ae9168 guibg=#674529 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#ae9168 guibg=#674529 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=NONE guibg=#ae9168 guisp=NONE gui=underline cterm=underline
  hi SignColumn guifg=NONE guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#5e544d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#963d3f guibg=NONE guisp=#963d3f gui=NONE cterm=NONE
  hi SpellCap guifg=#8b4830 guibg=NONE guisp=#8b4830 gui=NONE cterm=NONE
  hi SpellLocal guifg=#49576d guibg=NONE guisp=#49576d gui=NONE cterm=NONE
  hi SpellRare guifg=#6f4767 guibg=NONE guisp=#6f4767 gui=NONE cterm=NONE
  hi StatusLine guifg=#c2a273 guibg=#674529 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#674529 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#674529 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#674529 guibg=#c2a273 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#c2a273 guibg=#674529 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#744f2f guibg=#c2a273 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#ae9168 guisp=NONE gui=italic cterm=italic
  hi WarningMsg guifg=#8b4830 guibg=#c2a273 guisp=NONE gui=bold cterm=bold
  hi WildMenu guifg=#674529 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#963d3f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Typedef guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#3a6065 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#3a6065 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#3a6065 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#7e7268 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#5e544d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#7e7268 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#c2a273 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#7e7268 guibg=#c2a273 guisp=NONE gui=bold cterm=bold
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlEndTag guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssProp guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssClassName guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssClassNameDot guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassClass guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassClassChar guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lessVariable guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lessMixinChar guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lessAmpersandChar guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsParensRepeat Delimiter
  hi! link jsRepeatBraces Delimiter
  hi! link jsSwitchBraces Delimiter
  hi jsFunction guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFuncCall guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsAsyncKeyword guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalNodeObjects guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsNull guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptReserved guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptParens Delimiter
  hi typescriptNull guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptGlobalObjects guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi! link coffeeParen Delimiter
  hi coffeeInterpDelim guifg=#3a6065 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonBuiltinFunc guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonBuiltinType guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDottedName guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPackage guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goImport guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustExternCrate guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustKeyword guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustTrait guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustDeriveTrait guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpVarSelector guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi csUnspecifiedStatement guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csAsync guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csLogicSymbols guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartMetadata guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementPackage guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementInclude guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlFunction guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDecl guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDeclKeyword guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaFuncKeyword guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link luaBuiltIn Special
  hi dEnum guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dStorageClass guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dScopeDecl guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dOperator guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaKeywordModifier guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaSpecial guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaNameDefinition guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaInstanceDeclaration guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scalaCapitalWord guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link scalaSquareBrackets Delimiter
  hi! link scalaSquareBracketsBrackets Delimiter
  hi! link shQuote Delimiter
  hi! link shRange Delimiter
  hi! link shDerefVar Special
  hi zshSubst guifg=#3a6065 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshSubstDelim guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi zshDeref guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishKeyword guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fishCommandSub guifg=#3a6065 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonKeyword guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonQuote guifg=#3a6065 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyFile guifg=#3b604d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyBracket guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyNumber guifg=#963d3f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySlash guifg=#8b4830 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySection guifg=#6f4767 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyHeader guifg=#49576d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#8b4830 guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#963d3f guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#49576d guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#c27773 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#ce9861 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#7e7268 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#7e7268 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#7e7268 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#7e7268 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak guifg=NONE guibg=#ae9168 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=240 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=240 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=240 ctermbg=180 cterm=NONE
    hi Terminal ctermfg=240 ctermbg=180 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=180 cterm=NONE
  hi Conceal ctermfg=246 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=179 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=179 cterm=NONE
  hi CursorLineNr ctermfg=240 ctermbg=179 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=108 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=39 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=210 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=223 cterm=NONE
  hi Directory ctermfg=240 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=180 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=131 ctermbg=180 cterm=bold
  hi FoldColumn ctermfg=246 ctermbg=179 cterm=NONE
  hi Folded ctermfg=246 ctermbg=179 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=179 cterm=underline
  hi LineNr ctermfg=246 ctermbg=179 cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=239 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=239 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=246 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=240 ctermbg=179 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=179 cterm=NONE
  hi PmenuSel ctermfg=179 ctermbg=240 cterm=NONE
  hi PmenuThumb ctermfg=179 ctermbg=240 cterm=NONE
  hi Question ctermfg=65 ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=179 cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=179 cterm=NONE
  hi SpecialKey ctermfg=237 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=131 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=130 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=67 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=95 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=180 ctermbg=240 cterm=NONE
  hi StatusLineNC ctermfg=240 ctermbg=179 cterm=NONE
  hi TabLine ctermfg=240 ctermbg=179 cterm=NONE
  hi TabLineFill ctermfg=240 ctermbg=180 cterm=NONE
  hi TabLineSel ctermfg=180 ctermbg=240 cterm=NONE
  hi VertSplit ctermfg=241 ctermbg=180 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=179 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=179 cterm=italic
  hi WarningMsg ctermfg=130 ctermbg=180 cterm=bold
  hi WildMenu ctermfg=240 ctermbg=179 cterm=NONE
  hi Todo ctermfg=95 ctermbg=NONE cterm=NONE
  hi Label ctermfg=95 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=95 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=95 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=95 ctermbg=NONE cterm=NONE
  hi Title ctermfg=131 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=131 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=131 ctermbg=NONE cterm=NONE
  hi Error ctermfg=131 ctermbg=NONE cterm=bold
  hi Typedef ctermfg=131 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=131 ctermbg=NONE cterm=NONE
  hi Type ctermfg=130 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=130 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=67 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=67 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=67 ctermbg=NONE cterm=NONE
  hi Function ctermfg=67 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=67 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=65 ctermbg=NONE cterm=NONE
  hi String ctermfg=65 ctermbg=NONE cterm=NONE
  hi Character ctermfg=65 ctermbg=NONE cterm=NONE
  hi Number ctermfg=37 ctermbg=NONE cterm=NONE
  hi Float ctermfg=37 ctermbg=NONE cterm=NONE
  hi Special ctermfg=37 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=246 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=237 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=246 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=180 cterm=NONE
  hi ToolbarButton ctermfg=246 ctermbg=180 cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlEndTag ctermfg=95 ctermbg=NONE cterm=NONE
  hi cssProp ctermfg=130 ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=131 ctermbg=NONE cterm=NONE
  hi cssClassNameDot ctermfg=130 ctermbg=NONE cterm=NONE
  hi sassClass ctermfg=131 ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=131 ctermbg=NONE cterm=NONE
  hi lessVariable ctermfg=67 ctermbg=NONE cterm=NONE
  hi lessMixinChar ctermfg=130 ctermbg=NONE cterm=NONE
  hi lessAmpersandChar ctermfg=65 ctermbg=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsParensRepeat Delimiter
  hi! link jsRepeatBraces Delimiter
  hi! link jsSwitchBraces Delimiter
  hi jsFunction ctermfg=95 ctermbg=NONE cterm=NONE
  hi jsFuncCall ctermfg=67 ctermbg=NONE cterm=NONE
  hi jsAsyncKeyword ctermfg=95 ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=131 ctermbg=NONE cterm=NONE
  hi jsNull ctermfg=65 ctermbg=NONE cterm=NONE
  hi typescriptReserved ctermfg=65 ctermbg=NONE cterm=NONE
  hi! link typescriptParens Delimiter
  hi typescriptNull ctermfg=65 ctermbg=NONE cterm=NONE
  hi typescriptGlobalObjects ctermfg=131 ctermbg=NONE cterm=NONE
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi! link coffeeParen Delimiter
  hi coffeeInterpDelim ctermfg=37 ctermbg=NONE cterm=NONE
  hi pythonBuiltinFunc ctermfg=95 ctermbg=NONE cterm=NONE
  hi pythonBuiltinType ctermfg=131 ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=131 ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=131 ctermbg=NONE cterm=NONE
  hi goImport ctermfg=130 ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=131 ctermbg=NONE cterm=NONE
  hi rustKeyword ctermfg=65 ctermbg=NONE cterm=NONE
  hi rustTrait ctermfg=95 ctermbg=NONE cterm=NONE
  hi rustDeriveTrait ctermfg=130 ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=131 ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi csUnspecifiedStatement ctermfg=131 ctermbg=NONE cterm=NONE
  hi csAsync ctermfg=95 ctermbg=NONE cterm=NONE
  hi csLogicSymbols ctermfg=67 ctermbg=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartMetadata ctermfg=95 ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=131 ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=130 ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=95 ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=67 ctermbg=NONE cterm=NONE
  hi haskellDeclKeyword ctermfg=95 ctermbg=NONE cterm=NONE
  hi luaFuncKeyword ctermfg=95 ctermbg=NONE cterm=NONE
  hi! link luaBuiltIn Special
  hi dEnum ctermfg=130 ctermbg=NONE cterm=NONE
  hi dStorageClass ctermfg=67 ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=95 ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=131 ctermbg=NONE cterm=NONE
  hi scalaKeywordModifier ctermfg=95 ctermbg=NONE cterm=NONE
  hi scalaSpecial ctermfg=95 ctermbg=NONE cterm=NONE
  hi scalaNameDefinition ctermfg=130 ctermbg=NONE cterm=NONE
  hi scalaInstanceDeclaration ctermfg=131 ctermbg=NONE cterm=NONE
  hi scalaCapitalWord ctermfg=65 ctermbg=NONE cterm=NONE
  hi! link scalaSquareBrackets Delimiter
  hi! link scalaSquareBracketsBrackets Delimiter
  hi! link shQuote Delimiter
  hi! link shRange Delimiter
  hi! link shDerefVar Special
  hi zshSubst ctermfg=37 ctermbg=NONE cterm=NONE
  hi zshSubstDelim ctermfg=65 ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=130 ctermbg=NONE cterm=NONE
  hi fishKeyword ctermfg=95 ctermbg=NONE cterm=NONE
  hi fishCommandSub ctermfg=37 ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=67 ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=37 ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=65 ctermbg=NONE cterm=NONE
  hi StartifyBracket ctermfg=130 ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=131 ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=130 ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=95 ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=67 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=130 ctermbg=179 cterm=NONE
  hi ALEErrorSign ctermfg=131 ctermbg=179 cterm=NONE
  hi ALEInfoSign ctermfg=67 ctermbg=179 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=210 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=223 cterm=NONE
  hi ALEVirtualTextError ctermfg=246 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=246 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=246 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=246 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=179 cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=Brown ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Brown ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Brown ctermbg=LightGrey cterm=NONE
    hi Terminal ctermfg=Brown ctermbg=LightGrey cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=LightGrey cterm=NONE
  hi Conceal ctermfg=Brown ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Directory ctermfg=Brown ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=LightGrey cterm=bold
  hi FoldColumn ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi LineNr ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=Brown ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Brown ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Brown ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=LightGrey ctermbg=Brown cterm=NONE
  hi PmenuThumb ctermfg=LightGrey ctermbg=Brown cterm=NONE
  hi Question ctermfg=Green ctermbg=NONE cterm=NONE
  hi Search ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi SpecialKey ctermfg=Black ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=LightGrey ctermbg=Brown cterm=NONE
  hi StatusLineNC ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=Brown cterm=NONE
  hi VertSplit ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=LightGrey cterm=italic
  hi WarningMsg ctermfg=Yellow ctermbg=LightGrey cterm=bold
  hi WildMenu ctermfg=Brown ctermbg=LightGrey cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Label ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Title ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=bold
  hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Float ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Special ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Brown ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Black ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Brown ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi ToolbarButton ctermfg=Brown ctermbg=LightGrey cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlEndTag ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi cssProp ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=Red ctermbg=NONE cterm=NONE
  hi cssClassNameDot ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi sassClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=Red ctermbg=NONE cterm=NONE
  hi lessVariable ctermfg=Blue ctermbg=NONE cterm=NONE
  hi lessMixinChar ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi lessAmpersandChar ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsParensRepeat Delimiter
  hi! link jsRepeatBraces Delimiter
  hi! link jsSwitchBraces Delimiter
  hi jsFunction ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsFuncCall ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsAsyncKeyword ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=Red ctermbg=NONE cterm=NONE
  hi jsNull ctermfg=Green ctermbg=NONE cterm=NONE
  hi typescriptReserved ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link typescriptParens Delimiter
  hi typescriptNull ctermfg=Green ctermbg=NONE cterm=NONE
  hi typescriptGlobalObjects ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi! link coffeeParen Delimiter
  hi coffeeInterpDelim ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi pythonBuiltinFunc ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonBuiltinType ctermfg=Red ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=Red ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi goImport ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=Red ctermbg=NONE cterm=NONE
  hi rustKeyword ctermfg=Green ctermbg=NONE cterm=NONE
  hi rustTrait ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi rustDeriveTrait ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi csUnspecifiedStatement ctermfg=Red ctermbg=NONE cterm=NONE
  hi csAsync ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csLogicSymbols ctermfg=Blue ctermbg=NONE cterm=NONE
  hi! link dartCoreClasses Function
  hi dartMetadata ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlFunction ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=Blue ctermbg=NONE cterm=NONE
  hi haskellDeclKeyword ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi luaFuncKeyword ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi! link luaBuiltIn Special
  hi dEnum ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dStorageClass ctermfg=Blue ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=Red ctermbg=NONE cterm=NONE
  hi scalaKeywordModifier ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi scalaSpecial ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi scalaNameDefinition ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi scalaInstanceDeclaration ctermfg=Red ctermbg=NONE cterm=NONE
  hi scalaCapitalWord ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link scalaSquareBrackets Delimiter
  hi! link scalaSquareBracketsBrackets Delimiter
  hi! link shQuote Delimiter
  hi! link shRange Delimiter
  hi! link shDerefVar Special
  hi zshSubst ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi zshSubstDelim ctermfg=Green ctermbg=NONE cterm=NONE
  hi zshDeref ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi fishKeyword ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi fishCommandSub ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=Green ctermbg=NONE cterm=NONE
  hi StartifyBracket ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=Red ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=Blue ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=LightGrey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=LightGrey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi ALEVirtualTextError ctermfg=Brown ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Brown ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Brown ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=Brown ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=LightGrey cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: kraft         #c2a273           180               LightGrey
" Color: kraftalt      #ae9168           179               LightGrey
" Color: darkcover     #634022           239               Brown
" Color: cover         #674529           240               Brown
" Color: lightcover    #744f2f           241               Brown
" Color: red           #963d3f           131               Red
" Color: green         #3b604d           65                Green
" Color: orange        #8b4830           130               Yellow
" Color: blue          #49576d           67                Blue
" Color: magenta       #6f4767           95                Magenta
" Color: cyan          #3a6065           37                Cyan
" Color: lightbrown    #918175           245               Brown
" Color: brown         #7e7268           246               Brown
" Color: darkbrown     #5e544d           237               Black
" Color: lightred      #c27773           210               LightRed
" Color: lightgreen    #7fa37f           108               LightGreen
" Color: lightorange   #ce9861           223               LightYellow
" Color: lightblue     #7f8ca3           39                LightBlue
" Term colors: cover red green orange blue magenta cyan lightbrown
" Term colors: cover red green orange
" Term colors: blue magenta cyan lightbrown
" Color: unused #000000 0 0
" vim: et ts=2 sw=2
