" Name:         Ice Age
" Description:  Light, Cold, Calm Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-ice-age/
" License:      MIT && Anti-996
" Last Updated: Sat 13 Jul 2019 03:17:23 PM CST

" Generated by Colortemplate v2.0.0rc1

set background=light

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'ice-age'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Structure Type
hi! link Boolean Constant
hi! link Define PreProc
hi! link SpecialChar Special
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#4f596d', '#bd625d', '#548762', '#db6f32',
        \ '#4e74b2', '#7a5cb4', '#2a8783', '#eaedf4', '#4f596d', '#bd625d',
        \ '#548762', '#db6f32', '#4e74b2', '#7a5cb4', '#2a8783', '#eaedf4']
  if get(g:, 'light_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#4f596d guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#4f596d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#4f596d guibg=#eaedf4 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#4f596d guibg=#eaedf4 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#eaedf4 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#4f596d guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#8e98b2 guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#d0f2d0 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#d0def2 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#f2d0d1 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#f2e1d0 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#bd625d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#db6f32 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#8e98b2 guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#8e98b2 guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#f2d0d1 guisp=NONE gui=underline cterm=underline
  hi Search guifg=NONE guibg=#f2d0d1 guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#4f596d guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#eaedf4 guibg=#8e98b2 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#8e98b2 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#548762 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#bd625d guibg=NONE guisp=#bd625d gui=NONE cterm=NONE
  hi SpellCap guifg=#db6f32 guibg=NONE guisp=#db6f32 gui=NONE cterm=NONE
  hi SpellLocal guifg=#4e74b2 guibg=NONE guisp=#4e74b2 gui=NONE cterm=NONE
  hi SpellRare guifg=#7a5cb4 guibg=NONE guisp=#7a5cb4 gui=NONE cterm=NONE
  hi StatusLine guifg=#eaedf4 guibg=#8e98b2 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#4f596d guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#4f596d guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#4f596d guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#eaedf4 guibg=#8e98b2 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#e0e3ec guisp=NONE gui=italic cterm=italic
  hi WildMenu guifg=#4f596d guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#548762 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#548762 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#548762 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#548762 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#8e98b2 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#548762 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#bd625d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#8e98b2 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#4f596d guibg=#eaedf4 guisp=NONE gui=bold cterm=bold
  hi htmlTag guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTagN guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTagName guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlArg guifg=#548762 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssProp guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassProperty guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFunction guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi pythonStatement guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi rustExternCrate guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustDerive guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustSigil guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDecl guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDeclKeyword guifg=#7a5cb4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatement guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlPackageDecl guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi shFunction guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonKeyword guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonQuote guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi yamlKey guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlKey guifg=#4e74b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyFile guifg=#2a8783 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#db6f32 guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#bd625d guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#4e74b2 guibg=#e0e3ec guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#f2d0d1 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#f2e1d0 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#8e98b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak guifg=NONE guibg=#d0f2d0 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=60 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=60 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=60 ctermbg=255 cterm=NONE
    hi Terminal ctermfg=60 ctermbg=255 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=255 cterm=NONE
  hi Conceal ctermfg=103 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=254 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=254 cterm=NONE
  hi CursorLineNr ctermfg=60 ctermbg=254 cterm=NONE
  hi LineNr ctermfg=103 ctermbg=254 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=254 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=108 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=39 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=210 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=223 cterm=NONE
  hi Directory ctermfg=32 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=103 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=131 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=166 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=32 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=30 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=103 ctermbg=254 cterm=NONE
  hi Folded ctermfg=103 ctermbg=254 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=210 cterm=underline
  hi Search ctermfg=NONE ctermbg=210 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=103 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=60 ctermbg=254 cterm=NONE
  hi PmenuSel ctermfg=255 ctermbg=103 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=254 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=103 cterm=NONE
  hi Question ctermfg=65 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=131 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=166 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=32 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=97 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=255 ctermbg=103 cterm=NONE
  hi StatusLineNC ctermfg=60 ctermbg=254 cterm=NONE
  hi TabLine ctermfg=60 ctermbg=254 cterm=NONE
  hi TabLineFill ctermfg=60 ctermbg=254 cterm=NONE
  hi TabLineSel ctermfg=255 ctermbg=103 cterm=NONE
  hi VertSplit ctermfg=103 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=254 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=254 cterm=italic
  hi WildMenu ctermfg=60 ctermbg=254 cterm=NONE
  hi Title ctermfg=97 ctermbg=NONE cterm=NONE
  hi Label ctermfg=97 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=97 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=97 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=97 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=97 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=32 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=32 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=32 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=32 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=32 ctermbg=NONE cterm=NONE
  hi Special ctermfg=32 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=32 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=65 ctermbg=NONE cterm=NONE
  hi Function ctermfg=65 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=65 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=65 ctermbg=NONE cterm=NONE
  hi Type ctermfg=30 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=30 ctermbg=NONE cterm=NONE
  hi String ctermfg=30 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=30 ctermbg=NONE cterm=NONE
  hi Character ctermfg=30 ctermbg=NONE cterm=NONE
  hi Number ctermfg=30 ctermbg=NONE cterm=NONE
  hi Float ctermfg=30 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=103 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=65 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=103 ctermbg=NONE cterm=NONE
  hi Error ctermfg=131 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=103 cterm=NONE
  hi ToolbarButton ctermfg=60 ctermbg=255 cterm=bold
  hi htmlTag ctermfg=32 ctermbg=NONE cterm=NONE
  hi htmlTagN ctermfg=32 ctermbg=NONE cterm=NONE
  hi htmlTagName ctermfg=32 ctermbg=NONE cterm=NONE
  hi htmlArg ctermfg=65 ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=97 ctermbg=NONE cterm=NONE
  hi cssProp ctermfg=32 ctermbg=NONE cterm=NONE
  hi sassProperty ctermfg=32 ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=32 ctermbg=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi pythonStatement ctermfg=32 ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi rustExternCrate ctermfg=97 ctermbg=NONE cterm=NONE
  hi rustDerive ctermfg=97 ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=97 ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=32 ctermbg=NONE cterm=NONE
  hi haskellDeclKeyword ctermfg=97 ctermbg=NONE cterm=NONE
  hi perlStatement ctermfg=32 ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=30 ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=32 ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=32 ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=103 ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=32 ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=32 ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=30 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=166 ctermbg=254 cterm=NONE
  hi ALEErrorSign ctermfg=131 ctermbg=254 cterm=NONE
  hi ALEInfoSign ctermfg=32 ctermbg=254 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=210 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=223 cterm=NONE
  hi ALEVirtualTextError ctermfg=103 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=103 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=103 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=103 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=108 cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=White cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Directory ctermfg=Blue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=Blue ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightRed cterm=underline
  hi Search ctermfg=NONE ctermbg=LightRed cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Grey cterm=NONE
  hi Question ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Grey cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=LightGrey cterm=italic
  hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Title ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Label ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Special ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Green ctermbg=NONE cterm=NONE
  hi Function ctermfg=Green ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Green ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Green ctermbg=NONE cterm=NONE
  hi Type ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi String ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Character ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Number ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Float ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Green ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=White cterm=bold
  hi htmlTag ctermfg=Blue ctermbg=NONE cterm=NONE
  hi htmlTagN ctermfg=Blue ctermbg=NONE cterm=NONE
  hi htmlTagName ctermfg=Blue ctermbg=NONE cterm=NONE
  hi htmlArg ctermfg=Green ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi cssProp ctermfg=Blue ctermbg=NONE cterm=NONE
  hi sassProperty ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=Blue ctermbg=NONE cterm=NONE
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi pythonStatement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi! link phpParent Delimiter
  hi rustExternCrate ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi rustDerive ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi rustSigil ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=Blue ctermbg=NONE cterm=NONE
  hi haskellDeclKeyword ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi perlStatement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi shFunction ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsonQuote ctermfg=Grey ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi tomlKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=LightGrey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=LightGrey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi ALEVirtualTextError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=LightGreen cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: light         #eaedf4           ~                 White
" Color: lightgrey     #e0e3ec           ~                 LightGrey
" Color: grey          #8e98b2           ~                 Grey
" Color: dark          #4f596d           ~                 Black
" Color: green         #548762           ~                 Green
" Color: cyan          #2a8783           ~                 Cyan
" Color: blue          #4e74b2           ~                 Blue
" Color: magenta       #7a5cb4           ~                 Magenta
" Color: orange        #db6f32           ~                 Yellow
" Color: red           #bd625d           ~                 Red
" Color: lightred      #f2d0d1           210               LightRed
" Color: lightgreen    #d0f2d0           108               LightGreen
" Color: lightorange   #f2e1d0           223               LightYellow
" Color: lightblue     #d0def2           39                LightBlue
" Term colors: dark red green orange blue magenta cyan light
" Term colors: dark red green orange
" Term colors: blue magenta cyan light
" Color: unused #000000 0 0
